apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: delivery-cluster
  region: ap-northeast-2
  
nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 2
    volumeSize: 20
    volumeType: gp2
    volumeEncrypted: true
    volumeThroughput: 100
    volumeIops: 100
    volumeType: gp2