apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config-map
data:
  NOTIFICATION_HOST: "notification"
  NOTIFICATION_TCP_PORT: "3001"
  TCP_PORT: "3001"
  GRPC_URL: "0.0.0.0:3001"
  NOTIFICATION_GRPC_URL: "{{ .Chart.Name }}-notification-cluster-ip:3001"