apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config-map
data:
  HTTP_PORT: "3000"
  GRPC_URL: "0.0.0.0:3001"
  REFRESH_TOKEN_SECRET: "refresh_token_secret"
  ACCESS_TOKEN_SECRET: "access_token_secret"
  TCP_PORT: "3001"